### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by maybepiffpuffas** [logicguy1/Discord-Nitro-Gen-and-Checker#1]
Could you add proxy support because Discord limits the rate and blocks the connection for some time. Thank You.

**Comment by Bennitenni111** [comment]
**Sure, we will add proxies as soon as possible thanks for opening a ticket** @maybepiffpuffas 
- Benz

**Comment by logicguy1** [comment]
We have made the new proxy development branch where you can monitor the active development, we are currently having some issues with discord rate limiting all the proxies at once almost as if they got our real ip instead of the proxy but we are working on it tho feel free to contibude

**Comment by Bennitenni111** [comment]
**Oh, to notify you that we have added the proxy-system, which you may like to check with them, it auto-checks the proxies, you can check out the bunch system**

- Benz
