### ISSUE TITLE
this isnt working for me

### ISSUE THREAD

**Issue by dhairya-mistry** [logicguy1/Discord-Nitro-Gen-and-Checker#10]
this isn't  working, Idk what to do, here is a screenshot of what's happening you have to import a webhook, but I don't have any webhook honestly I just want the nitro

https://drive.google.com/file/d/1gA4D-TbfjhgI4v5Q3XtCGvJvy_AtzY7c/view?usp=sharing

**Comment by dhairya-mistry** [comment]
help me, help me i am dying

**Comment by dhairya-mistry** [comment]
i set up a discord web hook to my server but it still not working

**Comment by dhairya-mistry** [comment]
https://drive.google.com/file/d/1gA4D-TbfjhgI4v5Q3XtCGvJvy_AtzY7c/view?usp=sharing

**Comment by dhairya-mistry** [comment]
ummm is anyone gonna reply?

**Comment by Bennitenni111** [comment]
you should create webhook from **text channel**

**Comment by Bennitenni111** [comment]
+ you should read readme.md

Run that command
`pip install discord_webhook`

**Comment by gxzass** [comment]
You need to run the programme in cmd, not in python. 
- Open CMD
- Type "cd [file location]"
- Enter "py -3 -m pip install requests" (Or "python -m pip install requests")
- Enter "py -3 -m pip install discord_webhook" (Or "python -m pip install discord_webhook")
- Now run the script by typing "py -3 main.py" (Or "python main.py")
- Wait... the codes are very limited as its just random generated strings
