### ISSUE TITLE
Bug, and feature ig

### ISSUE THREAD

**Issue by stop-bark** [logicguy1/Discord-Nitro-Gen-and-Checker#11]
**Is your feature request related to a problem? Please describe.**
Ratelimits

**Describe the solution you'd like**
Add proxied version.

**Describe alternatives you've considered**
idk lol

**Additional context**
![image](https://user-images.githubusercontent.com/60797172/110239790-84155080-7f51-11eb-8356-22a5d136d6ff.png)
I added a status_code to the invalid and after a while its 429 aka ratelimited, so add proxies thanks

**Comment by BasToTheMax** [comment]
So you have to make some wait thing that it is waiting when it is ratelimited

**Comment by stop-bark** [comment]
> So you have to make some wait thing that it is waiting when it is ratelimited

or just add proxies, which would be better as it would be much faster than just waiting, and if a proxy gets ratelimited make that proxy wait like 10-20 seconds and then try again

**Comment by logicguy1** [comment]
Proxies doent work, tried everything

**Comment by logicguy1** [comment]
Also there is a branch for proxies if you have a solution for my proxy issue feel free to make a PR

**Comment by logicguy1** [comment]
Alright well i will just close the issue here
