### ISSUE TITLE
File Closes on start

### ISSUE THREAD

**Issue by Heromaex** [logicguy1/Discord-Nitro-Gen-and-Checker#12]
**Describe the bug**
As soon as I start the program, its instantly closing again

1. Go to your Explorer and change the files path (1 Folder up)
2. Click on the main.py file

**Expected behavior**
The file is being run

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: chrome
 - Version 2004

**Additional context**
I have installed the discord_embed module, so its not because of that

**Comment by Heromaex** [comment]
Im experienced in python, I will check if theres something wrong maybe

**Comment by logicguy1** [comment]
Did you run on windows `py -3 -m pip install discord_webhook`?

**Comment by Heromaex** [comment]
> Did you run on windows `py -3 -m pip install discord_webhook`?

Ive been running     pip install discord_webhook
