### ISSUE TITLE
problem opening the .py file

### ISSUE THREAD

**Issue by pancakesszz** [logicguy1/Discord-Nitro-Gen-and-Checker#16]
When I try to execute the .py file, it simply opens up for about half a second then closes. I think it has something to do with the "py -3 -m pip install discord_webhook" cmd, because I'm not sure where to execute it. If you could tell me where to put that cmd, it would be great.

**Comment by logicguy1** [comment]
You need it in in a terminal you can just search for cmd in the search area on windows

**Comment by maybepiffpuffas** [comment]
> You need it in in a terminal you can just search for cmd in the search area on windows

You could just pack it up in to an exe, it would be easier to use for people who don't know much about computers.

**Comment by logicguy1** [comment]
I might do that later thanks for your suggestion

**Comment by AstroOrbis** [comment]
Ill make one

**Comment by logicguy1** [comment]
Alright this issue seems to be solved, I'll close the issue now
