### ISSUE TITLE
any proof that it it works?

### ISSUE THREAD

**Issue by pjmangaming** [logicguy1/Discord-Nitro-Gen-and-Checker#6]
just want to ask if it work or if anyone has got an working code from it?

**Comment by logicguy1** [comment]
![image](https://user-images.githubusercontent.com/56993729/108640267-e9206f00-7498-11eb-879f-24f2d113db82.png)

**Comment by pjmangaming** [comment]
how long did it take , if i may ask?

**Comment by logicguy1** [comment]
I dont know but it may take a while

**Comment by pjmangaming** [comment]
when I get a valid code, does it send to the webhook or wait until all the progress to be done?

**Comment by logicguy1** [comment]
It sends it to the webhook as soon as it finds one

**Comment by z87x** [comment]
bruh I can clearly see that you edited the photo lmao

**Comment by logicguy1** [comment]
Wym thats not even mine

**Comment by C0V1D-19** [comment]
Lol why would he write that code if it were so fake..... it's not like we make stuff open source for someone who probably knows scratch to ask if it works I mean try it yourself.

**Comment by logicguy1** [comment]
Lmao ye

**Comment by logicguy1** [comment]
The code is written, there is no reason it should not work so ill close this descussion
