### ISSUE TITLE
Webhook bug

### ISSUE THREAD

**Issue by buraca27** [logicguy1/Discord-Nitro-Gen-and-Checker#7]
So i created a server and created a webhook
Then i copied the url of the webhook
Then i pasted when it said:
"Do you wish to use a discord webhook?
If so type it here or press enter to ignore:"
then i pressed enter and it just started to check the codes on the script intead of the webhook, im i doing something wrong?

**Comment by logicguy1** [comment]
No that's correct

**Comment by buraca27** [comment]
Then why it dosen't send the codes to the webhook?

**Comment by Bennitenni111** [comment]
Because you haven't got any valid codes
