### ISSUE TITLE
You should add the commands to use it on android

### ISSUE THREAD

**Issue by C0V1D-19** [logicguy1/Discord-Nitro-Gen-and-Checker#8]
Ik it sounds ridiculous but I'm sure we all have a old phone around and should put it to use so mabye use this on android......
it's just
```
----!!THIS IS WITH UNROOTED TERMUX!!----
git clone https://github.com/logicguy1/Discord-Nitro-Gen-and-Checker
pkg install python
pip install discord_webhooks
cd Discord-Nitro-Gen-and-Checker
python3 main.py
-------------------------------------
``` 
Good work btw

**Comment by C0V1D-19** [comment]
#Proof

![image](https://user-images.githubusercontent.com/62308340/109402787-48113880-791e-11eb-80f6-9081a4724b8a.jpeg)

**Comment by logicguy1** [comment]
Feel free to make a pr and update the readme

**Comment by C0V1D-19** [comment]
Ok will do later
