### ISSUE TITLE
do valid codes get saved to a txt document?

### ISSUE THREAD

**Issue by Kev2FreshYo** [logicguy1/Discord-Nitro-Gen-and-Checker#9]
do valid codes get saved to a txt document?

**Comment by C0V1D-19** [comment]
I would assume so let me look at the code

**Comment by C0V1D-19** [comment]
Yes it does

**Comment by logicguy1** [comment]
It does not

**Comment by BotAndis** [comment]
So how do I know when it generated a working code ?
I obviously can't watch the cmd window the whole time or did u implement it now that working codes are getting saved into txt ?
[Would Discord Hook tell me ?]

**Comment by logicguy1** [comment]
Working codes to be put into a txt file and if you use the web hook it will mention you in discord
